spring:
  application:
    name: auth
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        namespace: a29400b0-9f79-47a0-80df-6ceab61d3029
      config:
        namespace: a29400b0-9f79-47a0-80df-6ceab61d3029

  config:
    import:
      - nacos:common-env.yaml?refresh=true
      - nacos:actuator.yaml?refresh=true
      - nacos:spring-doc.yaml?refresh=true
      - nacos:federation-client.yaml?refresh=true
      - nacos:${spring.application.name}.yaml?refresh=true