spring:
  application:
    name: auth
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        namespace: a29400b0-9f79-47a0-80df-6ceab61d3029
      config:
        namespace: a29400b0-9f79-47a0-80df-6ceab61d3029

  config:
    import:
      - nacos:actuator.yaml?refresh=true
      - nacos:spring-doc.yaml?refresh=true
      - nacos:federation-client.yaml?refresh=true
      - nacos:${spring.application.name}.yaml?refresh=true

basic:
  cloud:
    login:
      access-token-time-to-live: 2h
      refresh-token-time-to-live: 30d